import { execFileSync, spawnSync } from "node:child_process";
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const root = process.cwd();
const manifest = JSON.parse(readFileSync(join(root, "release-manifest.json"), "utf8"));

describe("current public release documentation", () => {
  it("is deterministically generated from release-manifest.json", () => {
    expect(() => execFileSync(
      process.execPath,
      [join(root, "scripts", "render-current-release.mjs"), "--check"],
      { cwd: root, encoding: "utf8", stdio: "pipe" },
    )).not.toThrow();
  });

  it("names each release group and immutable engine source", () => {
    const markdown = readFileSync(join(root, "docs", "CURRENT_RELEASE.md"), "utf8");
    const engine = manifest.releaseGroups.engine;
    const studio = manifest.releaseGroups.studio;
    const site = manifest.releaseGroups.site;

    expect(markdown).toContain("# Current Memi release truth");
    expect(markdown).toContain(`CLI, npm, MCP, and Action | \`${engine.version}\``);
    expect(markdown).toContain(`\`${engine.sourceCommit}\``);
    expect(markdown).toContain(manifest.surfaces.githubRelease.url);
    expect(markdown).toContain(`Studio | \`${studio.version}\``);
    expect(markdown).toContain(`Memoire.Studio_${studio.version}_aarch64.dmg`);
    expect(markdown).toContain(`Website | \`${site.version}\``);
    expect(markdown).toContain("Generated from `release-manifest.json`. Do not edit this file manually.");
  });

  it("renders a candidate as unreleased and keeps the prior public activation path", () => {
    const fixture = mkdtempSync(join(tmpdir(), "memi-current-release-"));
    try {
      mkdirSync(join(fixture, "scripts", "lib"), { recursive: true });
      mkdirSync(join(fixture, "docs"), { recursive: true });
      cpSync(
        join(root, "scripts", "render-current-release.mjs"),
        join(fixture, "scripts", "render-current-release.mjs"),
      );
      cpSync(
        join(root, "scripts", "lib", "release-manifest.mjs"),
        join(fixture, "scripts", "lib", "release-manifest.mjs"),
      );
      const candidate = {
        ...manifest,
        releaseGroups: {
          ...manifest.releaseGroups,
          engine: {
            version: "2.6.3",
            state: "candidate",
            sourceCommit: null,
            releaseRecord: null,
            previousPublicRelease: {
              version: "2.6.2",
              sourceCommit: "ee3f3f00731a7a08c7616d4dfb14440165a86354",
            },
          },
        },
        surfaces: {
          ...manifest.surfaces,
          githubRelease: {
            ...manifest.surfaces.githubRelease,
            url: "https://github.com/sarveshsea/memi/releases/tag/v2.6.3",
          },
        },
      };
      writeFileSync(
        join(fixture, "release-manifest.json"),
        `${JSON.stringify(candidate, null, 2)}\n`,
      );

      const result = spawnSync(
        process.execPath,
        [join(fixture, "scripts", "render-current-release.mjs")],
        { cwd: fixture, encoding: "utf8" },
      );
      expect(result.status, result.stderr || result.stdout).toBe(0);
      const markdown = readFileSync(join(fixture, "docs", "CURRENT_RELEASE.md"), "utf8");
      expect(markdown).toContain("Engine candidate (unreleased)");
      expect(markdown).toContain("2.6.3 is not the current public release");
      expect(markdown).toContain("npx -y @memi-design/cli@2.6.2");
      expect(markdown).not.toContain("npx -y @memi-design/cli@2.6.3");
      expect(markdown).not.toContain("Source commit: `null`");
    } finally {
      rmSync(fixture, { recursive: true, force: true });
    }
  });
});
