import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const root = process.cwd();
const manifest = JSON.parse(readFileSync(join(root, "release-manifest.json"), "utf8"));

describe("current public release documentation", () => {
  it("is deterministically generated from release-manifest.json", () => {
    expect(() => execFileSync(
      process.execPath,
      [join(root, "scripts", "render-current-release.mjs"), "--check"],
      { cwd: root, encoding: "utf8", stdio: "pipe" },
    )).not.toThrow();
  });

  it("names each release group and immutable engine source", () => {
    const markdown = readFileSync(join(root, "docs", "CURRENT_RELEASE.md"), "utf8");
    const engine = manifest.releaseGroups.engine;
    const studio = manifest.releaseGroups.studio;
    const site = manifest.releaseGroups.site;

    expect(markdown).toContain("# Current Memi release truth");
    expect(markdown).toContain(`CLI, npm, MCP, and Action | \`${engine.version}\``);
    expect(markdown).toContain(`\`${engine.sourceCommit}\``);
    expect(markdown).toContain(manifest.surfaces.githubRelease.url);
    expect(markdown).toContain(`Studio | \`${studio.version}\``);
    expect(markdown).toContain(`Memoire.Studio_${studio.version}_aarch64.dmg`);
    expect(markdown).toContain(`Website | \`${site.version}\``);
    expect(markdown).toContain("Generated from `release-manifest.json`. Do not edit this file manually.");
  });
});
