#!/usr/bin/env python3
"""Generate deterministic paper assets from DesignWorkBench v2 evidence."""

from __future__ import annotations

import hashlib
import json
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
GENERATED = HERE / "generated"

BENCHMARK = ROOT / "benchmarks/designworkbench-v2/benchmark.json"
READINESS = ROOT / "docs/audits/memi-designworkbench-v2-readiness.json"
CALIBRATION = ROOT / "benchmarks/designworkbench-v2/PRACTITIONER_CALIBRATION.md"
EVIDENCE = ROOT / "benchmarks/designworkbench-v2/evidence/evidence.json"
PROTOCOL = HERE / "cross-harness-protocol.json"


def load(path: Path) -> dict:
    return json.loads(path.read_text())


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def tex_escape(value: str) -> str:
    return (
        value.replace("&", r"\&")
        .replace("%", r"\%")
        .replace("_", r"\_")
        .replace("#", r"\#")
    )


def write_csv(path: Path, headers: list[str], rows: list[list[object]]) -> None:
    lines = [",".join(headers)]
    lines.extend(",".join(str(value) for value in row) for row in rows)
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    benchmark = load(BENCHMARK)
    readiness = load(READINESS)["readiness"]
    protocol = load(PROTOCOL)

    splits = Counter(task["split"] for task in benchmark["tasks"])
    durations = [task["durationMinutes"] for task in benchmark["tasks"]]
    complexities = Counter(task["complexity"] for task in benchmark["tasks"])

    macros = {
        "PaperDate": "29 July 2026",
        "BenchmarkSchema": benchmark["schemaVersion"],
        "BenchmarkTracks": len(benchmark["tracks"]),
        "BenchmarkTasks": len(benchmark["tasks"]),
        "PublicTasks": splits["publicDevelopment"],
        "PrivateTasks": splits["privateTest"],
        "HoldoutTasks": splits["rollingHoldout"],
        "MinTaskMinutes": min(durations),
        "MaxTaskMinutes": max(durations),
        "MedianTaskMinutes": sorted(durations)[len(durations) // 2],
        "NegativeControls": len(benchmark["negativeControls"]),
        "RunnerProfiles": len(benchmark["runnerProfiles"]),
        "VerifiedRunners": readiness["verified"]["runners"],
        "PreparedFixtures": readiness["prepared"]["fixtures"],
        "VerifiedFixtures": readiness["verified"]["fixtures"],
        "Practitioners": readiness["verified"]["practitioners"],
        "CalibratedTracks": readiness["verified"]["calibratedTracks"],
        "MinimumPractitioners": benchmark["calibration"][
            "minimumPractitionersPerTrack"
        ],
        "MinimumExternalPractitioners": benchmark["calibration"][
            "minimumExternalPractitionersPerTrack"
        ],
        "ArtifactsPerPractitioner": benchmark["calibration"][
            "minimumArtifactsPerPractitioner"
        ],
        "RatingsPerArtifact": benchmark["calibration"][
            "minimumRatingsPerArtifact"
        ],
        "OverallAlpha": benchmark["calibration"]["overallReliabilityThreshold"],
        "TrackAlpha": benchmark["calibration"]["perTrackReliabilityFloor"],
        "HarnessConditions": len(protocol["conditions"]),
        "DevelopmentRepeats": protocol["execution"]["minimumIndependentRuns"],
        "ReleaseRepeats": protocol["execution"]["releaseCriticalRuns"],
    }
    macro_lines = [
        "% Generated by generate_paper_assets.py. Do not edit by hand."
    ]
    macro_lines.extend(
        f"\\newcommand{{\\{name}}}{{{value}}}" for name, value in macros.items()
    )
    (GENERATED / "metrics.tex").write_text("\n".join(macro_lines) + "\n")

    write_csv(
        GENERATED / "tracks.csv",
        ["track", "tasks", "artifactKinds", "rubricWeight"],
        [
            [
                f"T{index}",
                sum(task["trackId"] == track["id"] for task in benchmark["tasks"]),
                len(track["artifactKinds"]),
                sum(item["weight"] for item in track["rubric"]),
            ]
            for index, track in enumerate(benchmark["tracks"], start=1)
        ],
    )
    write_csv(
        GENERATED / "durations.csv",
        ["minutes", "tasks"],
        [[minutes, Counter(durations)[minutes]] for minutes in sorted(set(durations))],
    )
    write_csv(
        GENERATED / "complexities.csv",
        ["complexity", "tasks"],
        [[name, complexities[name]] for name in sorted(complexities)],
    )

    runner_lines = [
        r"\begin{tabularx}{\textwidth}{@{}p{0.19\textwidth}p{0.19\textwidth}X@{}}",
        r"\toprule",
        r"Runner & Current evidence & Required evidence contract \\",
        r"\midrule",
    ]
    verified_ids = set(
        load(READINESS)["evidence"]["verifiedRunnerIds"]
    )
    for runner in benchmark["runnerProfiles"]:
        status = "verified" if runner["id"] in verified_ids else "pending"
        evidence = ", ".join(runner["requiredEvidence"])
        runner_lines.append(
            f"{tex_escape(runner['title'])} & {status} & {tex_escape(evidence)} \\\\"
        )
    runner_lines.extend([r"\bottomrule", r"\end{tabularx}"])
    (GENERATED / "runners.tex").write_text("\n".join(runner_lines) + "\n")

    sources = [BENCHMARK, READINESS, CALIBRATION, EVIDENCE, PROTOCOL]
    digest_lines = [
        r"\begin{tabularx}{\textwidth}{@{}X>{\ttfamily\tiny\raggedright\arraybackslash}p{0.49\textwidth}@{}}",
        r"\toprule",
        r"Artifact & SHA-256 \\",
        r"\midrule",
    ]
    for source in sources:
        relative = source.relative_to(ROOT).as_posix()
        digest_lines.append(f"\\nolinkurl{{{relative}}} & {sha256(source)} \\\\")
    digest_lines.extend([r"\bottomrule", r"\end{tabularx}"])
    (GENERATED / "source_hashes.tex").write_text("\n".join(digest_lines) + "\n")

    print(
        json.dumps(
            {
                "generated": [
                    str(path.relative_to(ROOT))
                    for path in sorted(GENERATED.iterdir())
                ],
                "sources": {
                    str(path.relative_to(ROOT)): sha256(path) for path in sources
                },
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
