import { describe, expect, it } from "vitest";
import type { DesignToken } from "../../engine/registry.js";
import { exportTokens, generateTailwindExtend } from "../tokens.js";

const tokens: DesignToken[] = [
  makeToken("color/Primary", "color", { Light: "#ff5470", Dark: "#ff8094" }, "--color-primary"),
  makeToken("spaceSm", "spacing", { default: 8 }, "--space-sm"),
  makeToken("radius/card", "radius", { default: 12 }, "--radius-card"),
  makeToken("type/body", "typography", { default: 15 }, "--type-body"),
  makeToken("shadow/elevated", "shadow", { default: "0 8px 24px rgb(0 0 0 / 20%)" }, "--shadow-elevated"),
  makeToken("opacity/disabled", "other", { default: 0.5 }, "--opacity-disabled"),
  makeToken("empty", "other", {}, "--empty"),
];

describe("Figma token export", () => {
  it("maps every supported token category into CSS, JSON, Tailwind, and dark mode", () => {
    const result = exportTokens(tokens, "Light");

    expect(result.css).toContain("--color-primary: #ff5470");
    expect(result.css).toContain("--space-sm: 8px");
    expect(result.css).toContain("--radius-card: 12px");
    expect(result.css).toContain("--type-body: 15px");
    expect(result.css).toContain(".dark {");
    expect(result.css).toContain("--color-primary: #ff8094");
    expect(result.css).not.toContain("--empty:");
    expect(result.tailwindExtend).toEqual({
      colors: { "color-primary": "var(--color-primary)" },
      spacing: { "space-sm": "var(--space-sm)" },
      borderRadius: { "radius-card": "var(--radius-card)" },
      fontSize: { "type-body": "var(--type-body)" },
      boxShadow: { "shadow-elevated": "var(--shadow-elevated)" },
    });
    expect(result.json).toMatchObject({
      "color/Primary": "#ff5470",
      spaceSm: "8px",
      "opacity/disabled": "0.5",
    });
  });

  it("matches modes case-insensitively and falls back to the first value", () => {
    expect(exportTokens([tokens[0]], "light").json).toEqual({
      "color/Primary": "#ff5470",
    });
    expect(exportTokens([tokens[1]], "missing").json).toEqual({
      spaceSm: "8px",
    });
    expect(exportTokens([])).toEqual({
      css: ":root {\n}",
      tailwindExtend: {},
      json: {},
    });
  });

  it("generates a deterministic Tailwind extend module", () => {
    const output = generateTailwindExtend(tokens);
    expect(output).toContain("Auto-generated by Mémoire");
    expect(output).toContain("export const memoireTokens");
    expect(output).toContain("\"color-primary\": \"var(--color-primary)\"");
    expect(output).toContain("\"radius-card\": \"var(--radius-card)\"");
    expect(output.endsWith("};")).toBe(true);
  });
});

function makeToken(
  name: string,
  type: DesignToken["type"],
  values: DesignToken["values"],
  cssVariable: string,
): DesignToken {
  return { name, collection: "test", type, values, cssVariable };
}
